version: '3.1'

services:
  redis:
    image: redis:latest
  billing-service:
    image: my-hotswap-tomcat7:latest
    build:
      context: web/
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8081:8081"
      - "9000:9000"
    depends_on:
      - redis